### ISSUE TITLE
Add ability to run from the CLI (eg. ./validate <filename>)

### ISSUE THREAD

**Issue by clouserw** [mozilla/firefox-app-validator-manifest#29]
I wouldn't say this was a P1 requirement but the current validator can either spit out JSON for when it's used as a library or prettyprint text to the console which is pretty handy for testing stuff locally.  What do you think?

**Comment by operatorjen** [comment]
sounds reasonable - any reason why someone can't run this with their own node script as per the example in the README? we could also create the script for this module but it sounds like a standalone thing that isn't necessarily attached to this library. Could include it as a working example script though.

**Comment by clouserw** [comment]
No, I saw the example script.  I was just thinking it should be a part of the package we distribute.  :)

**Comment by operatorjen** [comment]
hmmm maybe i'll add it in a script dir!

**Comment by operatorjen** [comment]
I believe DevTools are working on CLI tools for validation and will encompass this feature on their end.
