### ISSUE TITLE
some properties are only valid for privileged/certified apps

### ISSUE THREAD

**Issue by eviljeff** [mozilla/firefox-app-validator-manifest#31]
origin
redirects
role
precompile (that might be missing altogether?)

**Comment by operatorjen** [comment]
https://github.com/mozilla/node-firefox-app-validator-manifest/blob/master/index.js#L476-L478 (origin)
https://github.com/mozilla/node-firefox-app-validator-manifest/commit/310cf19b204a4c194c7ef49ccafa3f02aa165c27

yeah looks like precompile is gone

**Comment by eviljeff** [comment]
I meant precompile is a valid property for packaged apps, but isn't listed in common.json
