### ISSUE TITLE
screen_size property?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/firefox-app-validator-manifest#33]
can't find this on MDN manifest page.  Is it new?

**Comment by operatorjen** [comment]
In the python code I see it here https://github.com/mozilla/app-validator/blob/master/appvalidator/specs/webapps.py#L169

Let me know if this is confirmed to be invalid so we can remove if necessary

**Comment by eviljeff** [comment]
I'm almost certain it got dropped from the early specifications.  Marketplace doesn't do anything with that field, and I can't see the runtime does either.

**Comment by operatorjen** [comment]
https://github.com/mozilla/node-firefox-app-validator-manifest/commit/7b293e48149af005d209a706f7b22fa554a1d221
