### ISSUE TITLE
Permissions should be validated per type

### ISSUE THREAD

**Issue by eviljeff** [mozilla/firefox-app-validator-manifest#35]
i.e. we shouldn't let a type=web app ask for device-storage:sdcard permission

**Comment by lmorchard** [comment]
FWIW, the python validator doesn't do this:

https://github.com/mozilla/app-validator/blob/master/appvalidator/specs/webapps.py#L645
https://github.com/mozilla/app-validator/blob/master/tests/test_webapp.py#L794

We've got [by-type lists of permissions](https://github.com/mozilla/node-firefox-app-validator-manifest/blob/master/test/test.index.js#L1110) that I copied over from the python. So, we can throw an error if any permissions appear other than those expected for the type. 

But, that will diverge from the original validator. Probably more of an FYI to note than a reason not to do this, though.

**Comment by eviljeff** [comment]
yeah... I was something that I always thought the python validator should do but never got around to logging a bug for it.
