### ISSUE TITLE
Do not enforce a pattern on the version property

### ISSUE THREAD

**Issue by eviljeff** [mozilla/firefox-app-validator-manifest#36]
I don't believe the spec requires the version property to be in any particular format

"chese5%uhdf  - 63 @" is valid afaik. It might be wise to encourage a more sensible format though I suppose

**Comment by lmorchard** [comment]
If it's not in the spec, from where would we get that format? The spec says "The User-Agent does not interpret this value in any way and is opaque to everyone but the application itself", so the sensibility of the format is in the eye of the app developer :neckbeard:

**Comment by eviljeff** [comment]
there isn't one, its just a string of any format.

**Comment by lmorchard** [comment]
Yeah, so what I'm saying is I don't think it's possible to come up with a format to close this issue. That, or this is more properly a spec bug than a validator issue

**Comment by eviljeff** [comment]
what I mean is there is a format specified in common.json now and there shouldn't be as version doesn't have a format according to the spec.

**Comment by fwenzel** [comment]
I think I understand @eviljeff and rephrased the Issue summary. Look good?

**Comment by eviljeff** [comment]
@fwenzel decoded my rambling correctly

**Comment by lmorchard** [comment]
Ah, that makes more sense, thanks!

**Comment by lmorchard** [comment]
(Also, I'm under-caffinated this morning and feeling a bit dense. Thanks for filing all these issues though, @eviljeff )
