### ISSUE TITLE
icons must be square

### ISSUE THREAD

**Issue by eviljeff** [mozilla/firefox-app-validator-manifest#37]
apologies if this is already enforced, I couldn't see it in the code.  As summary, icons must be square.  I'm not 100% if this is a Marketplace only requirement.

**Comment by lmorchard** [comment]
This isn't enforced, because this validator doesn't inspect images. All the manifest provides is a single dimension for `icons`, so there's no separate height/width to evaluate

**Comment by fwenzel** [comment]
Is that something a validator (this, or the _app_ validator) should cover? "You claim this is square but it isn't", or "you claim this file exists, but it doesn't"

**Comment by eviljeff** [comment]
its something a fully featured app validator should check.  (In the case of the icons: the file exists; its square; its a matching dimension to the manifest entry).  But which part of the 'stack' it should be in I'm not sure.

**Comment by lmorchard** [comment]
This is _just_ the manifest validator. I think a more comprehensive app validator is coming in a future project.

**Comment by operatorjen** [comment]
This would be covered in a separate module that would deal with specific size checks, etc.

**Comment by operatorjen** [comment]
bug created here https://bugzilla.mozilla.org/show_bug.cgi?id=1040902
