### ISSUE TITLE
validate() should return a promise

### ISSUE THREAD

**Issue by paulrouget** [mozilla/firefox-app-validator-manifest#41]
For now, `validate` is synchronous. But that might change. Also, future validation mechanisms might not be synchronous. So to be future-proof and coherent with other validation mechanisms, `validate()` should return a (already resolved) promise.

**Comment by operatorjen** [comment]
https://github.com/mozilla/firefox-app-validator-central/commit/77b8203900a52120f46c64a9db5e1ddcacb3d390
